spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-server-dev123
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-server-test456
